name: TimeTracker
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  setup:
    name: Set up TimeTracker Application
    runs-on: ubuntu-latest
    steps:
      # Checkout the code

      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Specify the Python version to use

      # Install dependencies
      - name: Install dependencies
        run: |
          #pip install -r requirements.txt
      # Verify installation
      
      - name: Verify setup
        run: |
          python src/time_tracker.py
          
